// src/components/RandomSection/RandomSection.vue
<style scoped>
.head {
  margin-top: 16px;
}
</style>

<template>
  <form class="card container">
    <div class="form-group head">
      <input
        class="form-control"
        placeholder="Name"
        :value="value.name"
        @input="onNameChange"
      />
    </div>
    <div class="form-group">
      <input
        class="form-control"
        placeholder="Length"
        :value="value.length"
        @input="onLengthChange"
      />
    </div>
    <div class="form-group">
      <label>Choices</label>
      <div class="form-check">
        <div>
          <input
            class="form-check-input"
            type="checkbox"
            :checked="value.useNumbers"
            @click="toggleUseNumbers"
          />
          <label>Numbers</label>
        </div>
        <div>
          <input
            class="form-check-input"
            type="checkbox"
            :checked="value.useLetters"
            @click="toggleUseLetters"
          />
          <label>Letters</label>
        </div>
      </div>
      <Button block variant="danger" @click="onDelete">Delete</Button>
    </div>
  </form>
</template>

<script lang="ts">
import Vue from "vue";
import Component from "vue-class-component";
import Button from "../Button.vue";
import { RandomSectionModel } from "../../services";

@Component({
  components: {
    Button,
  },
  props: {
    value: {
      type: RandomSectionModel,
      default() {
        return new RandomSectionModel(0);
      },
    },
  },
})
class RandomSection extends Vue {
  onNameChange(event: InputEvent) {
    event.preventDefault();

    let value = this.$props.value as RandomSectionModel;
    value.name = (event.target as HTMLInputElement).value;

    this.$emit("input", value);
  }

  onLengthChange(event: InputEvent) {
    let value = this.$props.value as RandomSectionModel;
    value.length = Number.parseInt((event.target as HTMLInputElement).value);

    this.$emit("input", value);
  }

  toggleUseNumbers() {
    let value = this.$props.value as RandomSectionModel;
    value.useNumbers = !value.useNumbers;

    this.$emit("input", value);
  }

  toggleUseLetters() {
    let value = this.$props.value as RandomSectionModel;
    value.useLetters = !value.useLetters;

    this.$emit("input", value);
  }

  onDelete(event: MouseEvent) {
    event.preventDefault();

    this.$emit("delete", event);
  }
}

export default RandomSection;
</script>

// src/components/RandomSection/RandomSection.tsx
import Card from '@mui/material/Card';
import CardContent from '@mui/material/CardContent';
import Checkbox from '@mui/material/Checkbox';
import FormControlLabel from '@mui/material/FormControlLabel';
import Stack from '@mui/material/Stack';
import Typography from '@mui/material/Typography';
import { Button } from '../Button';
import { TextField } from '../TextField';
import type { RandomSectionModel } from '../../services';

export interface RandomSectionProps {
  value: RandomSectionModel;
  onChange: (next: RandomSectionModel) => void;
  onDelete: () => void;
}

export function RandomSection({
  value,
  onChange,
  onDelete,
}: RandomSectionProps) {
  function update(partial: Partial<RandomSectionModel>) {
    const next = value.clone();
    Object.assign(next, partial);
    onChange(next);
  }

  return (
    <form
      onSubmit={(event) => {
        event.preventDefault();
      }}
    >
      <Card variant="outlined">
        <CardContent>
          <Stack spacing={2}>
            <TextField
              label="Name"
              value={value.name}
              onChange={(name) => update({ name })}
            />
            <TextField
              label="Length"
              type="number"
              value={value.length}
              onChange={(length) => update({ length: Number(length) || 0 })}
            />
            <Stack spacing={1}>
              <Typography variant="body1" sx={{ fontWeight: 500 }}>
                Choices
              </Typography>
              <FormControlLabel
                control={
                  <Checkbox
                    checked={value.useNumbers}
                    onChange={(event) =>
                      update({ useNumbers: event.target.checked })
                    }
                  />
                }
                label="Numbers"
              />
              <FormControlLabel
                control={
                  <Checkbox
                    checked={value.useLetters}
                    onChange={(event) =>
                      update({ useLetters: event.target.checked })
                    }
                  />
                }
                label="Letters"
              />
            </Stack>
            <Button
              variant="outlined"
              block
              startIcon={<span className="material-icons">delete</span>}
              onClick={(event) => {
                event.preventDefault();
                onDelete();
              }}
            >
              Delete
            </Button>
          </Stack>
        </CardContent>
      </Card>
    </form>
  );
}
